
import math
from itertools import zip_longest

def encryption(text: str) -> None:
    """
    Encrypts a string using a grid-based encryption method.

    The function takes a string, removes any spaces, and determines the grid
    dimensions (rows and columns) such that rows * columns >= length of the string.
    The string is then placed into the grid, and the ciphertext is generated by
    reading characters column-wise.

    Args:
        text (str): The input string to be encrypted.
    """
    chars = list(text.replace(" ", ""))
    n = len(chars)
    rows = int(math.sqrt(n))
    cols = rows if rows * rows >= n else rows + 1
    container = []

    for i in range(0, n, cols):
        container.append("".join(chars[i:i + cols]))

    col_ = [col for col in zip_longest(*container, fillvalue='')]

    print(" ".join("".join(t) for t in col_))

def main():
    """
    Main function to read input and call the encryption function.
    """
    s = input()
    encryption(s)

if __name__ == "__main__":
    main()